### PR TITLE
Test pull request – checks if Hound works fine with Thoughtbot's config

### PR DESCRIPTION
**Pull request by skalee**

### CODE REVIEW

**Comment by yosh1kura** [comment]
It looks like a very good renovation.
However, regrettable being a conflict

**Comment by ronaldtse** [comment]
@skalee can we merge this? Thanks!

**Comment by skalee** [comment]
@yosh1kura @ronaldtse 

Well… this pull request was never intended to be merged into master. I've created it only to test if Hound CI works correctly with our improved style guide. We were doing some bigger structural changes back then (see https://github.com/riboseinc/oss-guides/pull/3), and I needed some place to experiment. Apparently I forgot to close the pull request afterwards.

These experiments were quite successful, and our current style guide is highly inspired with them. You can find the current version of our style guide here: https://github.com/riboseinc/oss-guides. Moreover, everything worth merging (IMHO) is already on master since merging #57. I think that only leftovers are here, and I am going to close this pull request unless someone opposes.

That said, there is one thing to note. The style guide in this project wasn't updated for a while, and when you wrote your comments, it wasn't compatible with Rubocop 0.54. But it's a trivial change, and I've already took care of that in #61.

**Comment by ronaldtse** [comment]
Thank you @skalee ! Let’s mark the experiment a success and close it.

**Pull request closed without merging**
