### PR TITLE
Introduce Rubocop, use Ribose OSS style guide

### PR DESCRIPTION
**Pull request by skalee**
Style lint configuration comes from: https://github.com/riboseinc/oss-guides#ruby-projects

### CODE REVIEW

**Comment by skalee** [comment]
@ronaldtse @abunashir Rubocop & Hound configuration as discussed in #9.

Hould reported nothing, perhaps it's inactive, but I have no privileges to enable it for this repo. Rubocop returns over 100 violations at the moment, they come from the legacy code.

**Comment by ronaldtse** [comment]
Hound is active, let's see if it works after merging.

**Comment by ronaldtse** [comment]
Thanks @skalee !

**Comment by abunashir** [comment]
@skalee: The `hound` is active, and the way `hound` work is it will comment based on the changes we are doing in any PR, not the overall codebase.

image

That way it does not require us to instantly rewrite the whole code base for the style guide, but it ensures new codes follows the guidelines, and provide us the time to gradually fix our old code base to resolve those violations.

cc: @ronaldtse

**Pull request merged**
