### PR TITLE
Initialize a working test suite

### PR DESCRIPTION
**Pull request by skalee**
Rewrite spec helper, add a first spec, and prove that the test suite is working.

### CODE REVIEW

**Comment by skalee** [comment]
Looks like Hound does work.

**Comment by skalee** [comment]
@ronaldtse @abunashir Looks like the following comment does not pass the style check:

```
# -*- encoding: utf-8 -*-
# (c) 2017 Ribose Inc.
#
```

A blank line must be inserted right after the magic comment (lone hash doesn't pass either):

```
# -*- encoding: utf-8 -*-

# (c) 2017 Ribose Inc.
#
```

What should I do here? Should I keep that line (excessive IMO), remove the magic line (and drop support for Ruby 1.9 which is very old anyway), or update the Rubocop config?

**Comment by skalee** [comment]
Another question is about merging branches. Fast-forward or non-fast-forward fashion?

**Comment by ronaldtse** [comment]
We prefer a rebase and fast forward for simplicity in the resulting tree.

**Comment by abunashir** [comment]
@skalee: Regarding the magic comment on each specific file, I don't think we need it unless we have a very specific reason to support any version older than [Ruby's maintenance cycle.](https://www.ruby-lang.org/en/downloads)

Maintaining support for that older version is painful, especially when Ruby Core does not have any official support for that version. For a new gem like this one, I think `Ruby 2.1.9` is a pretty good minimum, what do you think @ronaldtse?

Edit: I did not notice we were using a magic comment in each file.

**Comment by ronaldtse** [comment]
I agree that the minimum version supported should be 2.1.9 or even newer. At least I know this gem isn't being used by versions less than 2.3.

**Pull request merged**
