### PR TITLE
Add Mongoid support

### LINKED ISSUE #24: Add Mongoid support
@ronaldtse any comments? Especially on this issue's importance?

### PR DESCRIPTION
**Pull request by skalee**
Allow masking in Mongoid models. Fixes #24.

### CODE REVIEW

**Comment by skalee** [comment]
I have no idea why builds fail. Tried two times and "continuous-integration/travis-ci/push" always passes whereas "continuous-integration/travis-ci/pr" does not. I need to investigate. Apart from that, it's complete.

**Comment by skalee** [comment]
It is extremely weird. Two Travis builds with same configuration, and same codebase, and same everything. Even build logs are mostly identical. But one of these builds fails all the time. Unless I think out something clever with fresh mind tomorrow, I will contact support.

Hound warnings come from my temporary commits where I am trying to debug these builds.

**Comment by ronaldtse** [comment]
@skalee , should we just merge this first? Don't want this to get out of sync with master.

**Comment by ronaldtse** [comment]
The latest builds are only failing for "WITHOUT_ACTIVERECORD=1" and "WITHOUT_MONGOID=1" at these lines.

`WITHOUT_ACTIVERECORD` failing at:
```console
      Failure/Error: expect(defined?(::ActiveRecord)).to be(nil)
      
        expected nil
             got #<String:3967460> => "constant"
      Shared Example Group: "Attr Masker gem feature specs" called from ./spec/features/active_record_spec.rb:26
      # ./spec/features/active_record_spec.rb:13:in `block (3 levels) in <top (required)>'
```

`WITHOUT_MONGOID` failing at:
```console
An error occurred while loading ./spec/features/active_record_spec.rb.
Failure/Error: module Mongoid::Config
NameError:
  uninitialized constant Mongoid
```

**Comment by skalee** [comment]
@ronaldtse These two failures you're talking about are expected. They are caused by some temporary commits I've added on top of this branch in my attempts to investigate Travis issues.

However, there are two Travis checks and both have different results. One I've marked on picture attached with a green arrow always succeeds whereas one marked with a red arrow always fails. And this puzzles me. Anyway, I've sent a message to Travis support team, let's wait for their response.

**Comment by ronaldtse** [comment]
@skalee are we ready to merge it? If so please go ahead 👍

**Comment by skalee** [comment]
Cleaned-up and merged!

**Comment by skalee** [comment]
@ronaldtse could you push v0.2.0 to Rubygems? I don't have privileges to do so. GitHub release is already created.

**Comment by ronaldtse** [comment]
Done!

**Pull request merged**
