### PR TITLE
Fix code formatting

### PR DESCRIPTION
**Pull request by skalee**
Consistent indentation, trailing spaces, etc.

### CODE REVIEW

**Comment by abunashir** [comment]
Good work @skalee! We are trying to maintain a consistency throughout our open source projects, What do you think about adding the `.rubocop` & `.hound` configuration from the [Ribose OSS Guide](https://github.com/riboseinc/oss-guides)?

cc: @ronaldtse

**Comment by ronaldtse** [comment]
Thanks @skalee ! @abunashir you're right, could you help add the relevant files? Thanks!

**Comment by skalee** [comment]
@abunashir I'm fine with Rubocop, however this gem is based on some other one, and for current master Rubocop reports "8 files inspected, 151 offenses detected".

**Comment by ronaldtse** [comment]
@skalee we should clean up / rewrite the legacy code to better standards since its purpose is now quite different.

**Comment by skalee** [comment]
@ronaldtse I know, I just wonder if it makes sense at this stage. Anyway, #10 is now merged.

**Pull request merged**
